// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEMotion.Infrastructure.DBContext;

#nullable disable

namespace STEMotion.Infrastructure.Migrations
{
    [DbContext(typeof(StemotionContext))]
    [Migration("20260128033152_ThanhDT_Fix_DBContext")]
    partial class ThanhDT_Fix_DBContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chapter_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chapter_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subject_id");

                    b.HasKey("ChapterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapter", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ConfigData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_data");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("game_code");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("GameId");

                    b.HasIndex("GameCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Game_GameCode");

                    b.HasIndex("LessonId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.GameResult", b =>
                {
                    b.Property<Guid>("GameResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_result_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int")
                        .HasColumnName("correct_answers");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayDuration")
                        .HasColumnType("int")
                        .HasColumnName("play_duration");

                    b.Property<DateTime>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("GameResultId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("IX_GameResult_PlayedAt");

                    b.HasIndex("StudentId", "GameId")
                        .HasDatabaseName("IX_GameResult_StudentId_GameId");

                    b.ToTable("GameResult", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("grade_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeLevel")
                        .IsUnique();

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chapter_id");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int")
                        .HasColumnName("estimated_time");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lessonName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.LessonContent", b =>
                {
                    b.Property<Guid>("LessonContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_content_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("FormulaLatex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formula_latex");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("media_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_content");

                    b.HasKey("LessonContentId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContent", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.ParentStudent", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudent", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subject_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId");

                    b.HasIndex("GradeId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("gradeLevel");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("roleId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Chapter.subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Game.lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.GameResult", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Game", "Game")
                        .WithMany("GameResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameResult.game_id");

                    b.HasOne("STEMotion.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GameResult.student_id");

                    b.Navigation("Game");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lesson.chapter_id");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.LessonContent", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LessonContent.lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.ParentStudent", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.User", "Parent")
                        .WithMany("StudentRelations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ParentStudent.parent_id");

                    b.HasOne("STEMotion.Domain.Entities.User", "Student")
                        .WithMany("ParentRelations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ParentStudent.student_id");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subject.grade_id");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User.role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameResults");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonContents");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.Navigation("ParentRelations");

                    b.Navigation("StudentRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
